name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Klonla
        uses: actions/checkout@v2

      - name: Python Kurulumu
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Bağımlılıkları Yükle
        run: |
          pip install -r requirements.txt

      - name: Model Eğit
        run: |
          python train.py

      - name: Modeli Kaydet
        uses: actions/upload-artifact@v2
        with:
          name: model
          path: model.pkl

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Klonla
        uses: actions/checkout@v2

      - name: Modeli İndir
        uses: actions/download-artifact@v2
        with:
          name: model
          path: .

      - name: Docker Build
        run: |
          docker build -t ml-api .
