name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Klonla
        uses: actions/checkout@v2

      - name: Python Kurulumu
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          pip install mlflow fastapi uvicorn joblib scikit-learn pandas pytest
          # DVC kaldırıldı

      - name: Veri Dosyasını Kontrol Et
        run: |
          if [ ! -f data.csv ]; then
            echo "Hata: data.csv bulunamadı! Lütfen dosyayı repo'ya ekleyin."
            exit 1
          fi

      - name: Model Eğit
        run: |
          python train.py

     

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Klonla
        uses: actions/checkout@v2

      - name: Docker Kurulumu
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Docker Build
        run: |
          docker build -t ml-api .