name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Klonla
        uses: actions/checkout@v2

      - name: Python Kurulumu
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Bağımlılıkları Yükle
        run: |
          pip install -r requirements.txt

      - name: Model Eğit
        run: |
          python train.py

      # - name: Testleri Çalıştır
      #   run: |
        #     pytest --maxfail=1 --disable-warnings -q
  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Python Kurulumu
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
          
      - name: Bağımlılıkları Yükle
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Modeli Oluştur
        run: |
          python train.py
          ls -la  # Oluşan dosyaları kontrol
          
      - name: Docker Build
        run: |
          docker build -t ml-api .