name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Klonla
        uses: actions/checkout@v2
        with:
          submodules: true  # DVC için gerekiyor

      - name: DVC Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y dvc

      - name: Python Kurulumu
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Bağımlılıkları Yükle
        run: |
          pip install --upgrade pip
          pip install dvc mlflow fastapi uvicorn joblib scikit-learn pandas pytest

      - name: DVC Pull (Verileri İndir)
        run: |
          dvc pull  # DVC remote ayarlıysa verileri çeker

      - name: Model Eğit (DVC Pipeline)
        run: |
          dvc repro

      - name: Testleri Çalıştır
        run: |
          pytest --maxfail=1 --disable-warnings -q

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Klonla
        uses: actions/checkout@v2

      - name: Docker Build
        run: |
          docker build -t ml-api .